all: pingserver pingclient1 pingclient2 pingclient3

pingserver: pingserver.c
	gcc -o pingserver pingserver.c

pingclient1: pingclient1.c
	gcc -o pingclient1 pingclient1.c

pingclient2: pingclient2.c
	gcc -o pingclient2 pingclient2.c

pingclient3: pingclient3.c
	gcc -o pingclient3 pingclient3.c